//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanhGiaCanBo.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DanhGiaCBEntities : DbContext
    {
        public DanhGiaCBEntities()
            : base("name=DanhGiaCBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_CanBo> tbl_CanBo { get; set; }
        public virtual DbSet<tbl_DanhGia> tbl_DanhGia { get; set; }
        public virtual DbSet<tbl_KhaoSat> tbl_KhaoSat { get; set; }
        public virtual DbSet<tbl_Quay> tbl_Quay { get; set; }
    }
}
