//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanhGiaCanBo.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CanBo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CanBo()
        {
            this.tbl_DanhGia = new HashSet<tbl_DanhGia>();
        }
    
        public int ID { get; set; }
        public string MaCB { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string GioiTinh { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgayLamViec { get; set; }
        public string Anh { get; set; }
        public string GioiThieu { get; set; }
        public Nullable<int> Quay_ID { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual tbl_Quay tbl_Quay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DanhGia> tbl_DanhGia { get; set; }
    }
}
