//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanhGiaCanBo.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DanhGia
    {
        public int ID { get; set; }
        public Nullable<int> CanBo_ID { get; set; }
        public Nullable<int> KhaoSat_ID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_CanBo tbl_CanBo { get; set; }
        public virtual tbl_KhaoSat tbl_KhaoSat { get; set; }
    }
}
