//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanhGiaCanBo.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Quay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Quay()
        {
            this.tbl_CanBo = new HashSet<tbl_CanBo>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string ND_HoTro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CanBo> tbl_CanBo { get; set; }
    }
}
